### ISSUE TITLE
Field descriptions

### ISSUE THREAD

**Issue by datagutten** [RuterNo/open-data#2]
There is no header with field names in the files. I checked stops.csv against [Googles sample](https://developers.google.com/transit/gtfs/examples/gtfs-feed) , but the fields do not match.
Can you add some documentation for what the fields contain?

**Comment by barslett** [comment]
Somehow, a wrong file set has been uploaded today. We are sorry, and will do our best to upload corrected data on Friday.



Sendt fra min Samsung Galaxy-smarttelefon.


-------- Opprinnelig melding --------
Fra: datagutten <notifications@github.com>
Dato: 06.07.2017 20:58 (GMT+01:00)
Til: RuterNo/open-data <open-data@noreply.github.com>
Ko: Subscribed <subscribed@noreply.github.com>
Emne: [RuterNo/open-data] Field descriptions (#2)


There is no header with field names in the files. I checked stops.csv against Googles sample<https://developers.google.com/transit/gtfs/examples/gtfs-feed> , but the fields do not match.
Can you add some documentation for what the fields contain?

-

**Comment by barslett** [comment]
Corrected data are published now.
